spring:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
  thymeleaf:
    cache: false