spring:
  h2:
    console:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/itku_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
  thymeleaf:
    cache: false
    
logging:
  file: /applogs/itku.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    com.youfchen: WARN
    org.hibernate: WARN